In [1]:
import spacy

In [2]:
nlp = spacy.load('en_core_web_lg')

In [3]:
nlp(u'lion').vector

array([ 1.8963e-01, -4.0309e-01,  3.5350e-01, -4.7907e-01, -4.3311e-01,
        2.3857e-01,  2.6962e-01,  6.4332e-02,  3.0767e-01,  1.3712e+00,
       -3.7582e-01, -2.2713e-01, -3.5657e-01, -2.5355e-01,  1.7543e-02,
        3.3962e-01,  7.4723e-02,  5.1226e-01, -3.9759e-01,  5.1333e-03,
       -3.0929e-01,  4.8911e-02, -1.8610e-01, -4.1702e-01, -8.1639e-01,
       -1.6908e-01, -2.6246e-01, -1.5983e-02,  1.2479e-01, -3.7276e-02,
       -5.7125e-01, -1.6296e-01,  1.2376e-01, -5.5464e-02,  1.3244e-01,
        2.7519e-02,  1.2592e-01, -3.2722e-01, -4.9165e-01, -3.5559e-01,
       -3.0630e-01,  6.1185e-02, -1.6932e-01, -6.2405e-02,  6.5763e-01,
       -2.7925e-01, -3.0450e-03, -2.2400e-02, -2.8015e-01, -2.1975e-01,
       -4.3188e-01,  3.9864e-02, -2.2102e-01, -4.2693e-02,  5.2748e-02,
        2.8726e-01,  1.2315e-01, -2.8662e-02,  7.8294e-02,  4.6754e-01,
       -2.4589e-01, -1.1064e-01,  7.2250e-02, -9.4980e-02, -2.7548e-01,
       -5.4097e-01,  1.2823e-01, -8.2408e-02,  3.1035e-01, -6.33

In [4]:
len(nlp(u'lion').vector) # vector is 300 dimensions

300

In [5]:
nlp(u'I went to the store yesterday').vector # an average of all the vectors in the document

array([ 2.96931654e-01,  1.60872161e-01, -2.36660346e-01, -2.98950193e-03,
        1.19809352e-01,  7.20685208e-03,  2.21248325e-02, -2.01756656e-01,
        1.12223327e-01,  2.37779999e+00, -3.69641930e-01,  1.75469965e-02,
        2.61175007e-01, -2.08925009e-01, -1.45439997e-01,  1.65076684e-02,
       -1.96774662e-01,  9.79952157e-01, -2.56616566e-02, -2.73080170e-02,
        3.13973390e-02,  7.68545046e-02,  4.79538478e-02,  7.06741661e-02,
       -1.33037820e-01,  8.17003325e-02, -2.70548552e-01, -2.74088830e-01,
       -1.88424662e-01, -6.20518327e-02, -1.55076608e-01,  5.78823350e-02,
        9.19855013e-02,  1.63234994e-01, -1.50521651e-01, -4.36317921e-03,
        6.28738329e-02,  1.53435245e-01, -1.06892489e-01, -1.02610148e-01,
       -6.53373003e-02,  2.07016873e-03,  3.63086648e-02, -1.39670014e-01,
       -2.02667224e-03,  2.64430910e-01, -2.71953344e-01, -1.86993673e-01,
        6.55175000e-02, -4.56795059e-02, -6.50448278e-02,  1.02172494e-01,
        2.06200838e-01,  

In [6]:
tokens = nlp(u'lion cat pet')

In [8]:
for token1 in tokens:
    for token2 in tokens:
        print(token1.text, token2.text, token1.similarity(token2))

lion lion 1.0
lion cat 0.52654374
lion pet 0.39923766
cat lion 0.52654374
cat cat 1.0
cat pet 0.7505456
pet lion 0.39923766
pet cat 0.7505456
pet pet 1.0


In [9]:
tokens = nlp(u'like love hate')

In [10]:
for token1 in tokens:
    for token2 in tokens:
        print(token1.text, token2.text, token1.similarity(token2))

like like 1.0
like love 0.65790397
like hate 0.6574652
love like 0.65790397
love love 1.0
love hate 0.6393099
hate like 0.6574652
hate love 0.6393099
hate hate 1.0


In [13]:
nlp.vocab.vectors.shape

(684831, 300)

In [14]:
tokens = nlp(u'dog cat nargle')

In [15]:
for token in tokens:
    print(token.text, token.has_vector, token.vector_norm, token.is_oov)

dog True 7.0336733 False
cat True 6.6808186 False
nargle False 0.0 True


In [16]:
from scipy import spatial

In [17]:
cosine_similarity = lambda vec1, vec2: 1 - spatial.distance.cosine(vec1, vec2)

In [18]:
king = nlp.vocab['king'].vector
man = nlp.vocab['man'].vector
woman = nlp.vocab['woman'].vector

In [19]:
new_vector = king - man + woman

In [20]:
computed_similarities = []
for word in nlp.vocab:
    if word.has_vector and word.is_lower and word.is_alpha:
        similarity = cosine_similarity(new_vector, word.vector)
        computed_similarities.append((word, similarity))

In [21]:
computed_similarities = sorted(computed_similarities, key=lambda item:-item[1])

In [22]:
print([t[0].text for t in computed_similarities[:10]])

['king', 'queen', 'prince', 'kings', 'princess', 'royal', 'throne', 'queens', 'monarch', 'kingdom']


the famous example of going to queen just results in king again haha

## Sentiment Analysis with VADER

In [23]:
import nltk

C:\Users\lukem\anaconda3\envs\nlp_course\lib\site-packages\sklearn\utils\validation.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  LARGE_SPARSE_SUPPORTED = LooseVersion(scipy_version) >= '0.14.0'


In [24]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\lukem\AppData\Roaming\nltk_data...


True

In [25]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [26]:
sid = SentimentIntensityAnalyzer()

In [27]:
a = "This is a good movie"

In [28]:
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.508, 'pos': 0.492, 'compound': 0.4404}

In [29]:
a = "This was the best, most awesome movie EVER MADE!!!"

In [30]:
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.425, 'pos': 0.575, 'compound': 0.8877}

In [31]:
a = 'This was the WORST movie that has ever disgraced the screen'

In [32]:
sid.polarity_scores(a)

{'neg': 0.465, 'neu': 0.535, 'pos': 0.0, 'compound': -0.8331}

In [33]:
import pandas as pd

In [34]:
df = pd.read_csv("../TextFiles/amazonreviews.tsv", sep='\t')

In [35]:
df.head()

label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...
1   pos  The best soundtrack ever to anything.: I'm rea...
2   pos  Amazing!: This soundtrack is my favorite music...
3   pos  Excellent Soundtrack: I truly like this soundt...
4   pos  Remember, Pull Your Jaw Off The Floor After He...

In [36]:
df['label'].value_counts()

neg    5097
pos    4903
Name: label, dtype: int64

In [37]:
df.dropna(inplace=True)

In [38]:
blanks = []
for i, lb, rv in df.itertuples():
    if type(rv) == str:
        if rv.isspace():
            blanks.append(i)

In [40]:
blanks # no blanks that we need to drop

[]

In [41]:
df.iloc[0]['review']

'Stuning even for the non-gamer: This sound track was beautiful! It paints the senery in your mind so well I would recomend it even to people who hate vid. game music! I have played the game Chrono Cross but out of all of the games I have ever played it has the best music! It backs away from crude keyboarding and takes a fresher step with grate guitars and soulful orchestras. It would impress anyone who cares to listen! ^_^'

In [42]:
sid.polarity_scores(df.iloc[0]['review'])

{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'compound': 0.9454}

In [43]:
df['scores'] = df['review'].apply(lambda review: sid.polarity_scores(review))

In [44]:
df.head()

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...

In [45]:
df['compound'] = df['scores'].apply(lambda d:d['compound'])

In [46]:
df.head()

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  compound  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...    0.9454  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...    0.8957  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...    0.9858  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...    0.9814  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...    0.9781

In [50]:
df['comp_score'] = df['compound'].apply(lambda s:'pos' if s >= 0 else 'neg')

In [51]:
df.head()

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  compound comp_score  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...    0.9454        pos  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...    0.8957        pos  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...    0.9858        pos  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...    0.9814        pos  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...    0.9781        pos

In [52]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [53]:
accuracy_score(df['label'], df['comp_score'])

0.7091

In [54]:
print(classification_report(df['label'], df['comp_score']))

              precision    recall  f1-score   support

         neg       0.86      0.51      0.64      5097
         pos       0.64      0.91      0.75      4903

   micro avg       0.71      0.71      0.71     10000
   macro avg       0.75      0.71      0.70     10000
weighted avg       0.75      0.71      0.70     10000



In [55]:
print(confusion_matrix(df['label'], df['comp_score']))

[[2623 2474]
 [ 435 4468]]


### Movie Reviews project

In [56]:
import numpy as np

In [57]:
df = pd.read_csv("../TextFiles/moviereviews.tsv", sep='\t')

In [58]:
df.head()

label                                             review
0   neg  how do films like mouse hunt get into theatres...
1   neg  some talented actresses are blessed with a dem...
2   pos  this has been an extraordinary year for austra...
3   pos  according to hollywood movies made in last few...
4   neg  my first press screening of 1998 and already i...

In [59]:
df.dropna(inplace=True)

In [60]:
blanks = []
for i, lb, rv in df.itertuples():
    if type(rv) == str:
        if rv.isspace():
            blanks.append(i)

In [61]:
blanks

[57,
 71,
 147,
 151,
 283,
 307,
 313,
 323,
 343,
 351,
 427,
 501,
 633,
 675,
 815,
 851,
 977,
 1079,
 1299,
 1455,
 1493,
 1525,
 1531,
 1763,
 1851,
 1905,
 1993]

In [62]:
df.drop(blanks, inplace=True)

In [63]:
df['label'].value_counts()

pos    969
neg    969
Name: label, dtype: int64

In [64]:
sid = SentimentIntensityAnalyzer()

In [65]:
df['scores'] = df['review'].apply(lambda rv: sid.polarity_scores(rv))

In [66]:
df['comp'] = df['scores'].apply(lambda d:d['compound'])

In [69]:
df['comp_label'] = df['comp'].apply(lambda s: 'pos' if s >= 0 else 'neg')

In [70]:
df.head()

label                                             review  \
0   neg  how do films like mouse hunt get into theatres...   
1   neg  some talented actresses are blessed with a dem...   
2   pos  this has been an extraordinary year for austra...   
3   pos  according to hollywood movies made in last few...   
4   neg  my first press screening of 1998 and already i...   

                                              scores    comp comp_label  
0  {'neg': 0.121, 'neu': 0.778, 'pos': 0.101, 'co... -0.9125        neg  
1  {'neg': 0.12, 'neu': 0.775, 'pos': 0.105, 'com... -0.8618        neg  
2  {'neg': 0.067, 'neu': 0.783, 'pos': 0.15, 'com...  0.9953        pos  
3  {'neg': 0.069, 'neu': 0.786, 'pos': 0.145, 'co...  0.9972        pos  
4  {'neg': 0.09, 'neu': 0.822, 'pos': 0.088, 'com... -0.7264        neg

In [71]:
accuracy_score(df['label'], df['comp_label'])

0.6367389060887513

In [72]:
print(classification_report(df['label'], df['comp_label']))

              precision    recall  f1-score   support

         neg       0.72      0.44      0.55       969
         pos       0.60      0.83      0.70       969

   micro avg       0.64      0.64      0.64      1938
   macro avg       0.66      0.64      0.62      1938
weighted avg       0.66      0.64      0.62      1938



In [73]:
print(confusion_matrix(df['label'], df['comp_label']))

[[427 542]
 [162 807]]
